version: '3.9'
services:
  verifier:
    build:
      dockerfile: Dockerfile
    ports:
      - 1235:1235
    environment:
      NODE_URL: "https://stardust.linksfoundation.com/node1"
      ALLOW_ORIGIN: "http://localhost"
      PORT: 1235
      DATABASE_URL: "verifier.db"
      RPC_PROVIDER: "https://json-rpc.evm.stardust.linksfoundation.com/sedimark-chain"


        