version: '3.9'
services:
  verifier:
    build:
      dockerfile: Dockerfile
    ports:
      - 1235:1235
    environment:
      NODE_URL: "https://api.tangle.stardust.linksfoundation.com/"
      ALLOW_ORIGIN: "http://localhost"
      PORT: 1235


        