/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: btzJgIV4PQh7yueQ8Wp89QRICatXz9V4H+t6+YrOYft3NwPDufZOKmYwwv9UGpGi3Pc7wjdEz2t8jNvjfIohXw==
 */

/* eslint-disable */
// tslint:disable

interface Challenges {
  expiration: string
  nonce: string & {readonly __brand?: 'challenges_nonce'}
  requester_did: string
}
export default Challenges;

interface Challenges_InsertParameters {
  expiration: string
  nonce: string & {readonly __brand?: 'challenges_nonce'}
  requester_did: string
}
export type {Challenges_InsertParameters}
