/**
 * !!! This file is autogenerated do not edit by hand !!!
 *
 * Generated by: @databases/pg-schema-print-types
 * Checksum: yX6czpqQe+QFHYrtbFPhojQYNXp2Gbh+aQ/eka7F+epeu3yS9GMJu4jF0NbFbouaA8YyQ8REBnA/EWhDPqep+Q==
 */

/* eslint-disable */
// tslint:disable

import Challenges, {Challenges_InsertParameters} from './challenges'

interface DatabaseSchema {
  challenges: {record: Challenges, insert: Challenges_InsertParameters};
}
export default DatabaseSchema;

function serializeValue(_tableName: string, _columnName: string, value: unknown): unknown {
  return value;
}
export {serializeValue}

export type {
  Challenges,
  Challenges_InsertParameters,
}
